### ISSUE TITLE
Midstream errors not working?

### ISSUE THREAD

**Issue by vytskalt** [by-nir/aws-lambda-zig#3]
I don't know if this is expected but I don't appear to be getting any indication that the invocation failed when calling the function url of the `demo:stream_throw` example:

```console
$ curl https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.lambda-url.eu-west-1.on.aws/
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

@Nirlah any idea what could be happening here?

**Comment by Nirlah** [comment]
The runtime doesn’t interfere with the raw payloads to/from the Lambda service; it’s up to you to catch the error and stream an appropriate response (or take any other action desired).

If you enable CloudWatch Logs for the function, using the Zig’s standard error logs should be tracked over there. Any unhandled error that is returned from the handler is automatically logged by the runtime. (please open a bug if this is not the case 😅)

**Comment by Nirlah** [comment]
Ok, it indeed seems that the _stream_throw_ demo no longer work – I will look into it...

**Comment by vytskalt** [comment]
Also this is unrelated to this issue but I saw that when calling Channel.write() the data is automatically flushed. In my case I have multiple byte arrays I want to send at the same time in a single chunk. Perhaps it would be better to move out the flush call to a separate Channel.flush() function? I could make a PR for this if you'd like.
